#!groovy

// Run this pipeline on the custom Maven Slave ('maven-appdev')
// Maven Slaves have JDK and Maven already installed
// 'maven-appdev' has skopeo installed as well.
node('maven-appdev') {
  // Define Maven Command. Make sure it points to the correct
  // settings for our Nexus installation (use the service to
  // bypass the router). The file nexus_openshift_settings.xml
  // needs to be in the Source Code repository.
  def mvnCmd = "mvn -s nexus_settings_openshift.xml"
  // def mvnCmd = "mvn"
  // Checkout Source Code
    stage('Checkout Source') {
     // Replace xyz-gogs with the name of your Gogs project
     // Replace the credentials with your credentials.
     echo "LUC ===> Checkout Source "
     git credentialsId: 'c7708a47f75058b2af1a526babab66d071aca221', url: 'https://github.com/lucpierson/ParksMap.git'
  }

  // The following variables need to be defined at the top level
  // and not inside the scope of a stage - otherwise they would not
  // be accessible from other stages.
  // Extract version and other properties from the pom.xml
  def groupId    = getGroupIdFromPom("parksmap/pom.xml")
  def artifactId = getArtifactIdFromPom("parksmap/pom.xml")
  def version    = getVersionFromPom("parksmap/pom.xml")

  // Set the tag for the development image: version + build number
  def devTag  = "${version}-${BUILD_NUMBER}"
  // Set the tag for the production image: version
  def prodTag = "${version}"

  // Using Maven build the Jar file
  // Do not run tests in this step
  stage('Build ') {
    echo "Building version ${devTag}"

    dir('parksmap') {
      // dir:"parksmap"
      echo "Current directory is :"
      sh "pwd"
      sh "${mvnCmd} clean package spring-boot:repackage -DskipTests -Dcom.redhat.xpaas.repo.redhatga"
    }
  }

  // Using Maven run the unit tests
  stage('Unit Tests') {
    echo "Running Unit Tests"

      dir('parksmap') {
      // dir:"parksmap"
      echo "Current directory is :"
      sh "pwd"
      // sh "${mvnCmd} test"
      }
  }

  // Using Maven call SonarQube for Code Analysis
  stage('Code Analysis') {
    echo "Running Code Analysis    -- skipping"

      dir('parksmap') {
      // dir:"parksmap"
      echo "Current directory is :"
      sh "pwd"
      // sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube-lpierson-sonarqube.apps.na37.openshift.opentlc.com/ -Dsonar.projectName=${JOB_BASE_NAME}-${devTag}"
      }
  }

  // Publish the built Jar file to Nexus
  stage('Publish to Nexus') {
    echo "======================> STAGE Publish to Nexus"

      dir('parksmap') {
      // dir:"parksmap"
      echo "Current directory is :"
      sh "pwd"
      sh "${mvnCmd} versions:set -DnewVersion=${devTag}"
      sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3-lpierson-nexus.apps.na37.openshift.opentlc.com/repository/releases/"
      }
  }

  // Build the OpenShift Image in OpenShift and tag it.
  stage('Build and Tag OpenShift Image') {
    echo "STAGE Building OpenShift container image parksmap:${devTag}"

      dir('parksmap') {
      // dir:"parksmap"
      echo "Current directory is :"
      sh "pwd"
      // Start Binary Build in OpenShift using the file we just published
      sh "oc start-build parksmap --follow --from-file=./target/parksmap.jar -n lpierson-parkmap-dev"
      // Tag the image using the devTag   
      openshiftTag alias: 'false', destStream: 'parksmap', destTag: devTag, destinationNamespace: 'lpierson-parkmap-dev', namespace: 'lpierson-parkmap-dev', srcStream: 'parksmap', srcTag: 'latest', verbose: 'false'
      } 
  }

  // Deploy the built image to the Development Environment.
  stage('Deploy to Dev') {
    echo "Deploying container image to Development Project"
    echo "STAGE Deploying container image to Development Project"

     dir('parksmap') {
      // dir:"parksmap"
      echo "Current directory is :"
      sh "pwd"


     // Update the Image on the Development Deployment Config
     sh "oc set image dc/parksmap parksmap=docker-registry.default.svc:5000/lpierson-parkmap-dev/parksmap:${devTag} -n lpierson-parkmap-dev"

     // Update the Config Map which contains the users for the parksmap application
     //sh "oc delete configmap parksmap-config -n lpierson-parkmap-dev"
     //sh "oc create configmap parksmap-config --from-file=./configuration/application-users.properties --from-file=./configuration/application-roles.properties -n lpierson-parkmap-dev"

     // Deploy the development application.

     openshiftDeploy depCfg: 'parksmap', namespace: 'lpierson-parkmap-dev', verbose: 'false', waitTime: '', waitUnit: 'sec'
     openshiftVerifyDeployment depCfg: 'parksmap', namespace: 'lpierson-parkmap-dev', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: '', waitUnit: 'sec'
     openshiftVerifyService namespace: 'lpierson-parkmap-dev', svcName: 'parksmap', verbose: 'false'
  }

  }

  // Run Integration Tests in the Development Environment.
  stage('Integration Tests') {
    echo "Running Integration Tests"
     echo "1.10   ===> Running Integration Tests"
    sleep 45

    // Create a new task called "healthz"
    sh "curl -i -u 'tasks:redhat1' -H 'Content-Length: 0' -X GET http://parksmap-lpierson-parkmap-prod.apps.na37.openshift.opentlc.com/ws/healthz/"


    // Retrieve task with id "1"
    // sh "curl -i -u 'parksmap:redhat1' -H 'Content-Length: 0' -X GET http://parksmap-lpierson-parkmap-dev.apps.na37.openshift.opentlc.com/ws/info"


    // Delete task with id "1"
    // sh "curl -i -u 'parksmap:redhat1' -H 'Content-Length: 0' -X DELETE http://parksmap-lpierson-parkmap-dev.apps.na37.openshift.opentlc.com/ws/info"

  }



  // Copy Image to Nexus Docker Registry
  stage('Copy Image to Nexus Docker Registry') {

    echo "3.11   ==> Copy image to Nexus Docker Registry"

    sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:admin123 docker://docker-registry.default.svc.cluster.local:5000/lpierson-parkmap-dev/parksmap:${devTag} docker://nexus-registry-lpierson-nexus.apps.na37.openshift.opentlc.com/parksmap:${devTag}"


    // Tag the built image with the production tag.
       // changing the prod tag as Applicaiton is production ready
       prodTag = devTag
       echo "the prod tag to use for the image in production:" + prodTag


    openshiftTag alias: 'false', destStream: 'parksmap', destTag: prodTag, destinationNamespace: 'lpierson-parkmap-prod', namespace: 'lpierson-parkmap-dev', srcStream: 'parksmap', srcTag: devTag, verbose: 'false'



  }

  // Blue/Green Deployment into Production
  // -------------------------------------
  // Do not activate the new version yet.

  def destApp   = "parksmap-green"
  def activeApp = ""

  stage('Blue/Green Production Deployment') {

    echo "3.12   ==> Blue/Green Deployment into Production"

    sh "oc get route parksmap -n lpierson-parkmap-prod -o jsonpath='{ .spec.to.name }' > activesvc.txt"
    activeApp = readFile('activesvc.txt').trim()
    if (activeApp == "parksmap-green") {
       destApp = "parksmap-blue"
    }
    echo "===== LUC =============> Active Application:      " + activeApp
    echo "===== LUC =============> Destination Application: " + destApp


    dir('parksmap') {

       echo "Current directory is :"
       sh "pwd"

       echo "the prod tag to use for the image in production:" + prodTag

       // Update the Image on the Production Deployment Config
       sh "oc set image dc/${destApp} ${destApp}=docker-registry.default.svc:5000/lpierson-parkmap-dev/parksmap:${prodTag} -n lpierson-parkmap-prod"

       // Update the Config Map which contains the users for the parksmap application
       sh "oc delete configmap ${destApp}-config -n lpierson-parkmap-prod --ignore-not-found=true"
       //sh "oc create configmap ${destApp}-config --from-file=./configuration/application-users.properties --from-file=./configuration/application-roles.properties -n lpierson-parkmap-prod"

       // Deploy the inactive application.

       openshiftDeploy depCfg: destApp, namespace: 'lpierson-parkmap-prod', verbose: 'false', waitTime: '', waitUnit: 'sec'
       openshiftVerifyDeployment depCfg: destApp, namespace: 'lpierson-parkmap-prod', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true', waitTime: '', waitUnit: 'sec'
       openshiftVerifyService namespace: 'lpierson-parkmap-prod', svcName: destApp, verbose: 'false'
    }
  }

  stage('Switch over to new Version') {
    input "Switch Production?"

    echo "3.13 Switching Production application to ${destApp}."

    sh 'oc patch route parksmap -n lpierson-parkmap-prod -p \'{"spec":{"to":{"name":"' + destApp + '"}}}\''
  }




}

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}

